spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NomeDoBanco
    username: username
    password: senha
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: minha-chave-secreta
    expiration: 9000000 # 150 minutos em ms
server:
  port: 8080